### ISSUE TITLE
Asych comp?

### ISSUE THREAD

**Issue by bitdom8** [mattjennings/svelte-modals#10]
Can we open and close like async comp here:

https://svelte.dev/repl/4517b2961a7e466d99d994f043448a82?version=3.18.1

Thanks for great lib

**Comment by mattjennings** [comment]
Good idea, I've added an implementation of this and it's available under `svelte-modals@next`. Here's an example:

https://svelte.dev/repl/6c777499c64d412d82a86bd5351a5ca6?version=3.46.2

I'll plan to release it for v1.1.0, but I'd appreciate any feedback you might have.

**Comment by mattjennings** [comment]
Released in [1.1.0](https://github.com/mattjennings/svelte-modals/releases/tag/1.1.0)

**Comment by bitdom8** [comment]
Thanks @mattjennings
