### ISSUE TITLE
Possible to keep all modals visible?

### ISSUE THREAD

**Issue by countnazgul** [mattjennings/svelte-modals#13]
Im trying to create something like this:
![image](https://user-images.githubusercontent.com/22850/166410599-4a81c417-64a5-437e-8f20-be614245ffb2.png)

By passing `$modals.length` I can make the necessary css changes (applying some `padding`/`margin` to each modal) to create the layout but my problem is that only the last/active modal is kept visible.

**Comment by mattjennings** [comment]
If you don't use the `isOpen` prop in your modal components they will all stay visible. 

However, if you wanted to have multiple modals open and close them individually in arbitrary order, there's no way to do that currently. `closeModal()` etc. will always closes the most recent first.

Maybe it would make sense to support closing modals by a generated id or something, I'll have to think about that.

**Comment by mattjennings** [comment]
`closeById` has been added to v2.0.0, so by ignoring `isOpen` that should enable this use case
