### ISSUE TITLE
error on opening

### ISSUE THREAD

**Issue by thisispete** [mattjennings/svelte-modals#14]
getting an error on opening modals, 

Using the example from the repo, it looks like it's trying to create the Modal but it's getting a PointerEvent instead of the modal class definition? 

<img width="1552" alt="Screen Shot 2022-05-18 at 14 54 35" src="https://user-images.githubusercontent.com/677565/169162548-09cf4104-6ffb-45dc-8b53-2368914aa632.png">

Svelte-modals 1.1
Svelte 3.48
SvelteKit 1.0.0-next.326

**Comment by mattjennings** [comment]
Are you by any chance passing `openModal` to an `on:click` instead of a handler function?

If not, can you reproduce this in a Svelte REPL? You can base it off [this one](https://svelte.dev/repl/2f2d171a9ea7458191904cb2feb5a54c?version=3.48.0)

**Comment by thisispete** [comment]
yep onclick. 

seeing it open if I use
`      onMount(() => {
 		openModal(Modal, { title: "Alert", message: "This is an alert" })
	})`

**Comment by thisispete** [comment]
oh, I see, my bad, I had `on:click={openModal}`  should be `on:click={handleClick}` 

```
 const handleClick = () => {
    openModal(Modal, { title: "Alert", message: "This is an alert" })
  }
 ```
