### ISSUE TITLE
Event Handling

### ISSUE THREAD

**Issue by MentalGear** [mattjennings/svelte-modals#18]
Thank you for this great library! It's much more idiomatic than svelte-simple-modal!
However, there's no mention of event handling, and the standard svelte way doesn't seem to work.

**Is your feature request related to a problem? Please describe.**
I try to dispatch an event from my modal component to the `<Modals on:message={handleModalDialogButton}>` tag in the overlying component.

**Describe the solution you'd like**
Ideally, the normal svelte event dispatch would work out of the box.

**Describe alternatives you've considered**
Using a store.

**Comment by mattjennings** [comment]
Unfortunately the only way to pass data up is through callback props. It is indirectly shown in the examples for the [Managing your Modals](https://svelte-modals.mattjennings.io/managing-your-modals) section, but as also mentioned in #7, I should have a more clear page explaining this. 

If [svelte ever supports a way to forward all events up](https://github.com/sveltejs/svelte/issues/2837) this would be an easy feature to add. But until that day comes (if it does), callback props are the only way for now.

**Comment by MentalGear** [comment]
Not even a store?

**Comment by mattjennings** [comment]
Could you elaborate on what you mean?

**Comment by MentalGear** [comment]
Yeah, it''s a pity with event forwarding. Gone is the ease and simplicity when trying to open multiple modals. :/
There's also a whole spec discussion going on in: https://github.com/sveltejs/rfcs/pull/60

I was wondering if it would be possible to forward an event (or global event object), if you were to simply on:message on all intermediary components of your Modals system.

A bit like the svelte example were an inner elements forwards an event with on:message to the topmost level.
https://svelte.dev/tutorial/event-forwarding

**Comment by mattjennings** [comment]
Can you share your use case for wanting to handle events in `<Modals />`? IMO it doesn't make sense to have event handlers there, they should be on a per-modal basis. In which case #17 would be a good solution until there's a way to provide event handlers at the time of `openModal`.

**Comment by mattjennings** [comment]
I might have a solution here, should have a PR this week. It requires creating a custom event dispatcher, but it would allow you to handle events like so:

```js
openModal(MyModal, props, {
   on: {
        message: (event) =>  { ... }
   }
})
```

The modal would have to dispatch the event using a custom dispatch method, but effectively works the same as normal event dispatching:

```html
<script>
import { createModalEventDispatcher } from 'svelte-modals'

const dispatch = createModalEventDispatcher()

dispatch('message', { ... })
</script>
````

**Comment by mattjennings** [comment]
you can try it here https://svelte.dev/repl/40c3ee5b548f4c75bacf88b088259c66?version=3.49.0

**Comment by MentalGear** [comment]
This is great, thank you so much @mattjennings for this and your overall work on my favorite modal solution for svelte! (and sorry for the late reply!)
