### ISSUE TITLE
lazy-loading: typescript error 2345

### ISSUE THREAD

**Issue by sysmat** [mattjennings/svelte-modals#26]
**Describe the bug**
- using doc: https://svelte-modals.mattjennings.io/lazy-loading#lazy-loading
- typescript error:

```
Argument of type '() => Promise<typeof import("../Modal.svelte")>' 
is not assignable to parameter of type 'SvelteModalComponent<unknown> | SvelteModalComponent<unknown>[]'

```

**Additional context**
- modal works

**Comment by mattjennings** [comment]
thanks @sysmat , this should be fixed now in 1.2.1
