### ISSUE TITLE
What is the best way to pass data from the modal to the parent?

### ISSUE THREAD

**Issue by theelims** [mattjennings/svelte-modals#28]
I want to have a selection list on my modal and need to pass the result one level up. What is the best way to do so? I'm a svelte beginner so I might be missing the obvious here. 

Same would apply for a form inside the modal. 

Many thanks for the help.

**Comment by mattjennings** [comment]
Currently the best way is to use a prop on the modal as a callback with the value you want to pass up. Checkout the [Managing your Modals](https://svelte-modals.mattjennings.io/managing-your-modals) section for an example

**Comment by theelims** [comment]
That's what I've tried in the first place but I couldn't make it work. 

I tested it again and it works now. Obviously I got the syntax wrong in my first attempts. 

Thanks for your help.
