### ISSUE TITLE
use a svelte resolve configuration in package.json

### ISSUE THREAD

**Issue by stalkerg** [mattjennings/svelte-modals#30]
I see the next message:
16:36:56 [vite-plugin-svelte] WARNING: The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.

svelte-modals@1.2.1

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve for details.

**Comment by mattjennings** [comment]
thanks for reporting this, it should be fixed in 1.3.0

**Comment by stalkerg** [comment]
@mattjennings Hello, still an issue:
```
19:46:17 [vite-plugin-svelte] WARNING: The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.

svelte-modals@1.3.0

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve for details.
```

**Comment by mattjennings** [comment]
@stalkerg can you provide a repro? I do not see this error when using `@sveltejs/vite-plugin-svelte@2.4.3`.

I updated the package.json according to the FAQ in https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve. So if it's still happening then I'm not sure why.

What the FAQ suggested:

```diff
// package.json
  "files": ["dist"],
  "svelte": "dist/index.js",
+ "exports": {
+   ".": {
+     "svelte": "./dist/index.js"
+   }
  }
  ```
  
  What svelte-modals has:
  
  ```json
  "svelte": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "svelte": "./dist/index.js"
    }
  },
  ```

**Comment by stalkerg** [comment]
Seems like in debug mode possible to find a reason: https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/src/index.js#L185 but seems like if you have `"svelte"` it can produce it such warning it during SSR.

**Comment by mattjennings** [comment]
interesting. both the FAQ and svelte-package suggest having both the old "svelte" and the one in exports for backwards compatibility reasons.

can you share what the debug log prints for you?

**Comment by stalkerg** [comment]
> can you share what the debug log prints for you?

yeah, I am trying to reproduce it, it's happened randomly during the dev process.

**Comment by stalkerg** [comment]
@mattjennings finally find a reason!
```
vite:vite-plugin-svelte resolve difference for svelte-modals@1.3.0 svelte-modals - svelte: "/home/stalkerg/projects/mjv-art.org/spa/node_modules/svelte-modals/dist/index.js", vite: "/home/stalkerg/projects/mjv-art.org/spa/node_modules/svelte-modals/dist/index.js?v=73e39ece" +3ms
```

for some reason, we are using an extra `v` argument for svelte-modals.

**Comment by mattjennings** [comment]
@stalkerg huh, good find! this seems like it might have something to do with vite [prebundling](https://vitejs.dev/guide/features.html#npm-dependency-resolving-and-pre-bundling) svelte-modals. Perhaps some of your imports are using the prebundle, and others aren't? Maybe you could try out [some of these settings](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#excluding-libraries-from-prebundling) and see if it fixes the issue.

Either way, I'm not entirely sure what I can do here as I've done what vite-plugin-svelte's FAQ suggests to setup the library. This might be something for them to look at.
