### ISSUE TITLE
Svelte 5

### ISSUE THREAD

**Issue by mattjennings** [mattjennings/svelte-modals#35]
Svelte 5 is out now. Most features with svelte-modals should just work, though there seems to be some changes to transitions that mess up [deferred transitions](https://svelte-modals.com/transitions#transitions-between-modals). If not for this I'd feel comfortable releasing a 1.4.0 with a peerDependency update to add 5.0.0, but I think it's appropriate to do a 2.0.0 that makes use of Svelte 5 APIs and addresses some of the current outstanding issues.

If you need to use svelte-modals 1.3.0 with Svelte 5 in the meantime, you can simply ignore the peerDependency warning or if using npm install with `--legacy-peer-deps`, and just be aware of the potential breaking changes to deferred transitions.

**Comment by faulander** [comment]
when will the 1.3.0 be available?

**Comment by mattjennings** [comment]
hoping for v2 this weekends, just depends on how much time i can find for it. it's pretty much done pending documentation, current version can be found here https://svelte-modals-git-svelte-5-matt-jennings-projects-da50e5f9.vercel.app/usage/getting-started

**Comment by mattjennings** [comment]
released as 2.0.0 #37
