### ISSUE TITLE
 Modals don't show when using Routify and/or Capacitor

### ISSUE THREAD

**Issue by Zettexe** [mattjennings/svelte-modals#4]
**Describe the bug**
I tried using [svelte-capacitor](https://github.com/drannex42/svelte-capacitor) template and adding svelte-modals but the modals don't seem to work at all and without error messages

**Reproduction**
1. git clone [https://github.com/drannex42/svelte-capacitor](https://github.com/drannex42/svelte-capacitor)
2. npm install
3. npm install svelte-modals
4. Add basic examples from svelte-modals readme
5. npm run dev:start

**Comment by mattjennings** [comment]
I just ran into this yesterday. There's a Vite bug that causes this but the work around is to add this to your vite.config.js:

```js
  optimizeDeps: {
    exclude: ['svelte-modals'],
  }
```

**Comment by Zettexe** [comment]
Yep, seems to work just fine with that included

**Comment by mattjennings** [comment]
awesome. This is the [particular issue](https://github.com/vitejs/vite/issues/3910) if you're curious, but vite-plugin-svelte will hopefully automate this soon as a temporary workaround.
