### ISSUE TITLE
Allow scrolling the modal if the modal height width is more than the screen.

### ISSUE THREAD

**Issue by Star3Lord** [mattjennings/svelte-modals#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mattjennings** [comment]
You are in complete control of the styling for your modals, so it's a matter of updating the css in your modal components.

Please remember to fill out the issue templates for any future issues.

**Comment by nohea** [comment]
FYI: i found adding these to the example code allows scrolling:
```

  .contents {
    max-height: 400px;
    overflow: auto;
  }
```
