### ISSUE TITLE
Add example showing passing object from modal to component

### ISSUE THREAD

**Issue by AsafAgranat** [mattjennings/svelte-modals#7]
**Is your feature request related to a problem? Please describe.**
I went over the docs several times and I could not find an example showcasing how to pass event/object from a modal to the component it was launched from

**Describe the solution you'd like**
Could you kindly add an example, for example a confirmation dialog, whereby a response (i.e "OK"/"Cancel") is passed back to the launching component

Great project btw!

**Comment by mahyuddin** [comment]
1. Could you share the complete code of Managing your Modals example in REPL?
2. How to send back parameter from Modal to parent? In svelte eventdispatcher, we can use event.detail to get back latest value of props from Modal.

**Comment by mattjennings** [comment]
@mahyuddin i remade it here: https://svelte.dev/repl/af984ac79aec4a6e8ca2fdb0ea14e84b?version=3.49.0

it's not quite the same in terms of styling but logic is the same. If you want to see the exact code, check out the component I linked in the previous comment.

The only way to send data back to the parent is through a callback prop, as mentioned above, and as demonstrated in the repl. It is currently not possible to listen to events emitted by the modal but I welcome any PRs that would add support for it.

**Comment by mattjennings** [comment]
[modals.open](https://svelte-modals.mattjennin.gs/api/modals/#modalsopen) can now resolve with a value in 2.0.0
